app/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults
from django.views.generic import TemplateView

admin.site.index_title = "Site administration"
admin.site.name = "Django Admin"
admin.site.site_header = "Django administration"
admin.site.site_title = "Django site admin"

urlpatterns = [
    path("", TemplateView.as_view(template_name="index.html"), name="index"),
    path("accounts/", include("allauth.urls")),
    path("admin/", admin.site.urls),
    path("users/", include("users.urls"), name="users"),
]

if settings.DEBUG:
    urlpatterns.extend(
        [
            path("__debug__/", include("debug_toolbar.urls")),
            path(
                "400/",
                defaults.bad_request,
                kwargs={"exception": Exception("Bad Request")},
            ),
            path(
                "403/",
                defaults.permission_denied,
                kwargs={"exception": Exception("Permission Denied")},
            ),
            path(
                "404/",
                defaults.page_not_found,
                kwargs={"exception": Exception("Not Found")},
            ),
            path("500/", defaults.server_error),
        ],
    )
    urlpatterns.extend(static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))
    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

app/users/urls.py
from django.urls import path

from users import views

app_name = "users"

urlpatterns = [
    path(route="profile/", view=views.ProfileView.as_view(), name="profile"),
]

app/users/models.py
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass

app/users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView


class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = "users/profile.html"

app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" href="{% static 'img/favicon.ico' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
        crossorigin="anonymous" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  {% block extra_head %}{% endblock %}
  <title>{% block title %}{% endblock %}</title>
</head>
<body>
  {% include "components/header.html" %}
  {% include "components/messages.html" %}
  <main>{% block content %}{% endblock %}</main>
  {% include "components/footer.html" %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
          crossorigin="anonymous"></script>
  <script src="{% static 'js/script.js' %}"></script>
  {% block extra_body %}{% endblock %}
</body>
</html>

app/templates/components/footer.html
<footer class="py-3 my-4">
  <ul class="nav justify-content-center pb-3 mb-3">
    <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Home</a></li>
    <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Features</a></li>
    <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Pricing</a></li>
    <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">FAQs</a></li>
    <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">About</a></li>
  </ul>
  <p class="text-center text-body-secondary">© 2024 Company, Inc</p>
</footer>

app/templates/components/header.html
<header class="container-fluid mb-4">
  <nav class="navbar navbar-expand-lg">
    <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample11" aria-controls="navbarsExample11" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse d-lg-flex" id="navbarsExample11">
        <a class="navbar-brand col-lg-3 me-0" href="{% url 'index' %}">
          <svg width="40" height="40" xmlns="http://www.w3.org/2000/svg">
            <rect x="2" y="2" width="36" height="36" style="fill:#DEDEDE;stroke:#555555;stroke-width:2"/>
          </svg>
          Logo Text
        </a>

        <ul class="navbar-nav col-lg-6 justify-content-lg-center">
          <li class="nav-item"><a class="nav-link active" aria-current="page" href="#">Home</a></li>
          <li class="nav-item"><a class="nav-link" href="#">Link</a></li>
          <li class="nav-item"><a class="nav-link disabled" aria-disabled="true">Disabled</a></li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" aria-expanded="false">Dropdown</a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="#">Action</a></li>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>
        </ul>

        {% if not user.is_authenticated %}
        <ul class="navbar-nav mb-lg-0 col-lg-3 justify-content-lg-end">
          <li class="nav-item"><a class="nav-link" href="{% url 'account_login' %}">Login</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'account_signup' %}">Register</a></li>
        </ul>
        {% else %}
        <ul class="navbar-nav mb-lg-0 col-lg-3 justify-content-lg-end">
          <li class="nav-item"><a class="nav-link" href="{% url 'users:profile' %}">Profile</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'account_logout' %}">Logout</a></li>
        </ul>
        {% endif %}
      </div>
    </div>
  </nav>
</header>

app/templates/components/messages.html
{% if messages %}
  <div class="container">
    {% for message in messages %}
      <div class="message alert alert-dismissible fade show text-white fixed-bottom container shadow" role="alert" data-bs-theme="dark">
        {{ message }}
        <button class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    {% endfor %}
  </div>
{% endif %}

app/templates/index.html
{% extends "base.html" %}

{% block title %}Index{% endblock %}

{% block content %}
  <div class="container">
    <h1>Index</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugit, nulla?</p>
  </div>
{% endblock %}

app/users/templates/users/base.html
{% extends "base.html" %}

app/users/templates/users/profile.html
{% extends "users/base.html" %}

{% block title %}Profile{% endblock %}

{% block content %}
  <div class="container">
    <h1>Welcome, {{ user.username }}!</h1>
    <nav>
      <a href="{% url 'account_change_password' %}">Change Password</a>
      <a href="{% url 'account_email' %}">Change Email</a>
    </nav>
  </div>
{% endblock %}